#!/usr/bin/env bash
# Backs up MySQL databases into a dated tar file

# Use mysqldump to create a backup of all databases
mysqldump -u root -p"$1" --all-databases > backup.sql

# Create a tarball (compressed archive) with the backup file
tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
